[Internal] Improve Changelog by grouping changes

diff --git a/.github/workflows/push.yml b/.github/workflows/push.yml
--- a/.github/workflows/push.yml
+++ b/.github/workflows/push.yml
@@ -54,3 +54,26 @@ jobs:
         run: |
           # Exit with status code 1 if there are differences (i.e. unformatted files)
           git diff --exit-code
+
+  commit-message:
+    runs-on: ubuntu-latest
+    if: ${{ github.event_name == 'pull_request' }}
+    steps:
+      - name: Checkout
+        uses: actions/checkout@v3
+        with:
+          fetch-depth: 0
+
+      - name: Validate Tag
+        run: |
+          TAG=$(echo ${{ github.event.pull_request.title }} | sed -ne 's/\[\(.*\)\].*/\1/p')
+          echo "Found tag {$TAG}"
+          # The status code for grep will be 1 if no match, and 0 if a match.
+          # Store in variable to hide the actual grep result from the console output.
+          MATCH=$(cat .codegen/changelog_config.yml | grep "tag: \"\[$(echo $TAG)\]\"")
+
+      - name: Log failure
+        if: failure()
+        run: |
+          echo "Invalid or missing tag in commit message"
+          exit 1
